### ISSUE TITLE
Noisy errors when deleting temp files

### ISSUE THREAD

**Issue by ollieglass** [ajtulloch/sklearn-compiledtrees#23]
Sometimes when creating compiled trees I see ignored exceptions about deleting tempfiles.

I haven't yet got an stand alone example that recreates this - it doesn't always happen - but on this line in my app:
```
    model = compiledtrees.CompiledRegressionPredictor(model, n_jobs=16)
```

Sometimes many of these are produced:
```
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7f37801484a8>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/tempfile.py", line 589, in __del__
    self.close()
  File "/usr/lib/python3.5/tempfile.py", line 585, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/compiledtrees_n7ydnhys.cpp'
```

The closest issue I've found is https://bugs.python.org/issue23755, but it's not exactly the same. `NamedTemporaryFile`s in `sklearn-compiledtrees` are being created with `delete=True`, and `unlink` isn't called on them.

In `/tmp` I have hundreds of `.ccp` and `.o` files. Although they are small, I expect this could eventually become a problem.

**Comment by mwojcikowski** [comment]
I have never saw such error on Linux. Maybe `clang` is deleting source files when compiling? We have no such errors on CI either.

Can you make sure that those files are not from previous runs of your app, ie. those which has raised exception. I think, that tempfiles in such situation of not clean exit files might not be pruned.

We create files with `delete=True` on Mac and Linux and I don't think we can take control over them any further. The story is much different on windows, where the `.so` files might, by design, be left in place due to a Windows bug which prevent open files to by loaded via `dlopen(...)`.

**Comment by ollieglass** [comment]
I'm running this on Linux actually, Ubuntu 16.04.1 LTS (I develop on Mac and deploy to Linux). Funny enough it hasn't happened on Mac. 

I just deleted all the .cpp, .o and .so files in /tmp, ran again, and I get the same ignored exceptions.

I had a look in `code_gen.py`. Perhaps the temp files could be created without the `delete=True` option, and manually delete them after closing. Annoying to have to do this, but I can't think of a better solution right now.

**Comment by mwojcikowski** [comment]
OK, the exceptions are there, but do the files are left in place in `/tmp`?

I don't think we could do better than Python with cleaning up this mess by manually unlinking files (although we do it for Windows, which bugs me). Maybe we could manually call `[del f for f in files]` after we compile the code and not relay on python random calls to destructors?

Finally can you supply a shortest script reproducing such error? I'd like to check if it comes up on my Linux boxes.

The only reason for them are issues related to the type of file-system used. What is yours? My ext4 setups seam fine.

**Comment by ollieglass** [comment]
There's no files left in temp, they must have been from an earlier run. Perhaps I stopped the script with ctrl-c and they didn't get closed. It's a separate issue, but it would be nice to have a way of handling that.

If Python is cleaning up properly, perhaps it'd be ok to suppress these errors?

I'm trying to recreate it in isolation but haven't got a script for that yet. I can't share the full app that this is happening in.

I'm on ext4 on Linux. I'm running it on Mac now and also seeing the errors there.

**Comment by ollieglass** [comment]
I found the exceptions stop being thrown if I switch from using `multiprocessing.Pool` to `joblib.Parallel` in another part of my code that runs before the call to `compiledtrees`. 

It's a strange error and I'm not sure what's causing it, but as I have a fix I'm fine to leave it.

**Comment by mwojcikowski** [comment]
Oh, that indeed might be the reason: try pickling and unpickling temp file. It does not play well.
