### ISSUE TITLE
Delete temp files if compilation is terminated

### ISSUE THREAD

**Issue by ollieglass** [ajtulloch/sklearn-compiledtrees#25]
This came up in https://github.com/ajtulloch/sklearn-compiledtrees/issues/23 where I suspect breaking with ctrl-c caused temp file to be left around. Other things could terminate a compilation too, and it'd be nice to clear temp files if that happens.

One way to do this: do all compilation in a named temp folder, and have a finally clause that deletes that folder.

**Comment by mwojcikowski** [comment]
`NamedTemporaryFiles` are deleted on `KeyboardInterrupt` or other Exceptions. If you `kill`, especially `kill -9` the files will remain however we try to delete them. There is simply no way around it.

Testcase:

```
from tempfile import NamedTemporaryFile
from time import sleep

tmp = NamedTemporaryFile(prefix='testexit_')

sleep(60)
```

**Comment by ollieglass** [comment]
Oh, sorry, I could have checked that myself.
