### ISSUE TITLE
Building source on mac

### ISSUE THREAD

**Issue by shkyang** [ajtulloch/sklearn-compiledtrees#29]
Trying to play with the package a bit and build from source, I'm on 10.13.

python setup.py build_ext --verbose

...
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: Command "cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.13-intel-2.7/compiledtrees/_compiled.o -lm -o build/lib.macosx-10.13-intel-2.7/compiledtrees/_compiled.so -Wl,--allow-multiple-definition" failed with exit status 1

Looks like clang doesn't like the flag, and -m is also deprecated in clang, so I go ahead and remove the flag entirely (the build succeeds).

PYTHONPATH=. python3 benchmarks/bench_compiled_tree.py 
...
ImportError: dlopen(~/sklearn-compiledtrees/compiledtrees/_compiled.so, 2): Symbol not found: _PyCObject_Type

Any ideas what I'm doing wrong?

**Comment by mwojcikowski** [comment]
MacOS also requires GCC for installation. Unfortunately clang is not supported for now.
