### ISSUE TITLE
support for RandomForestClassifier

### ISSUE THREAD

**Issue by danstowell** [ajtulloch/sklearn-compiledtrees#3]
This library sounds like a great technique! If I read the README correctly, it only supports regressors, not yet classifiers. It would be great if it could support classifiers too - in particular, in my case, RandomForestClassifier.

**Comment by danstowell** [comment]
Hi - just so I understand, are this and #4 closed as "done" or "not to be done"? I checked the commits and didn't see it. Maybe you're just closing old stuff...

**Comment by ajtulloch** [comment]
Whoops - yeah, I just got another request for this, so I can do this for you if you'd like. It's pretty straightforward.

**Comment by danstowell** [comment]
Hi - yes, if you're willing, I'd love to benchmark it against the default for my big datasets!

**Comment by bkellerman** [comment]
Any progress on RandomForestClassifier support? I'm looking to use the probabilities from the RF.  If this is far off, I can fork and get hacking.

**Comment by pixelou** [comment]
+1, I would also like to have support for RF

**Comment by ajtulloch** [comment]
I don't really have time for this at the moment - it should be a fun exercise though for anyone who wants to do it though. Just modifying codegen is all that should be needed.

**Comment by mwojcikowski** [comment]
I'll have a try in my spare time. DecisionTreeClassifier differs from DecisionTreeRegressor by addition of probability methods, otherwise it should be the same trees. We'll have to test them on some set larger than few samples.

**Comment by lesshaste** [comment]
+1 for the classifier modification. It would be really great. Has there been any progress?

**Comment by maxtepkeev** [comment]
+1

**Comment by akshaykhushu** [comment]
does this support RandomForestClassifier??

**Comment by mwojcikowski** [comment]
Classifier is supported on the latest git master
