### ISSUE TITLE
Writing to temp file instead of list.

### ISSUE THREAD

**Issue by mwojcikowski** [ajtulloch/sklearn-compiledtrees#7]
Wouldn't it make more sense to write to temporary file directly from code generator instead of appending lines to list, then joining it and writing? I have quite big models (pickle ~1.5GB). Compiling is slow and a bit memory hungry... If you think it's alright I can make a PR.

**Comment by ajtulloch** [comment]
Sure, that sounds reasonable. If your model is 1.5GB, I would be surprised if GCC doesn't choke on the massive source code that will be generated BTW.

**Comment by mwojcikowski** [comment]
Yes that's true. Tree.cpp is around 3.2GB and gcc consumes over 40GB of RAM, but RF pickle afterwards is around 300MB (from those 1.5GB) and it performs much faster. I have to do some benchmarks. I didn't find a way to limit gcc RAM usage, although it might not be even possible to do that...

**Comment by mwojcikowski** [comment]
The final plan is to make fallowing changes to the code:
- lines are written straight to the file
- `lines` method would be replaced by `file` method witch returns the temp filename
- trees will be in separate files + ensemble file; gcc will compile those separately with joblib.Parallel

Let me know what do you think.
