### ISSUE TITLE
Convert input descriptors to np.float32 automatically

### ISSUE THREAD

**Issue by mwojcikowski** [ajtulloch/sklearn-compiledtrees#9]
Current behavior is to trow an exception when descriptors aren't of certain type (np.float32). Can we use `sklearn.utils.check_array() `instead to make the descriptors valid? Or at least `X.astype(DTYPE)` [here](https://github.com/ajtulloch/sklearn-compiledtrees/blob/master/compiledtrees/compiled.py#L131). This would be preferable solution, since it;s the behavior of sklearn. Otherwise compiled predictor is not  drop-in replacement for original one. If you feel uncomfortable with such change, can we at least add a switch to constructor to do so (default=False).

**Comment by ajtulloch** [comment]
Sure, go for it.

**Comment by ajtulloch** [comment]
Thanks very much @mwojcikowski.
